package Mine;

public class PC_Burner {
    static void main(String[] args) {
        double a = 0.00 ;
        double b = 0.00 ;
        while (a < 1000000000.00 && b < 1000000000.00) {
            ++a;++b;
            System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(a++);
            System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));System.out.println(b++);
            System.out.println(a + b);
            System.out.println(a*b);
            System.out.println(a/b);
            System.out.println(a%b);
            System.out.println((a*b)*(a/b)/(a + b));
        }
    }
}
